### ISSUE TITLE
400 Missing Required Header for CSRF protection.

### ISSUE THREAD

**Issue by circleJ** [eBay/griffin#48]
when i run in docker it works, but is there a way content with my local hive database? And when i try run GRIFFIN  at local，i can use my hive database，but the job cant submit **Caused by: org.springframework.web.client.HttpClientErrorException: 400 Missing Required Header for CSRF protection.**  so，i turn  the csrf protection value from true to FALSE ，the job can submit and the state was running，but after that the state became unknow，and i got a WARN from my  terminal **BA, emp_testm-BA-test-1507603777000job Instance has some null filed (state or appId). java.lang.NullPointerException**. could anybody hlep me with this? 
THANKS!

**Comment by circleJ** [comment]
2017-10-10 19:40:00.078 ERROR 15598 --- [ryBean_Worker-2] org.quartz.core.ErrorLogger              : Job (BA.emp_testm-BA-test-1507603777000 threw an exception.

org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-2.2.2.jar!/:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.2.jar!/:na]
Caused by: org.springframework.web.client.HttpClientErrorException: 400 Missing Required Header for CSRF protection.
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700) ~[spring-web-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653) ~[spring-web-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613) ~[spring-web-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:380) ~[spring-web-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.apache.griffin.core.job.SparkSubmitJob.execute(SparkSubmitJob.java:104) ~[classes!/:0.1.6-incubating-SNAPSHOT]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.2.jar!/:na]
	... 1 common frames omitted
